### ISSUE TITLE
WLEDAraSync.exe not working

### ISSUE THREAD

**Issue by ZorK766** [ShadyNawara/WLEDAuraSync#2]
Hi, currently playing with many WLED devices, I'm very interested in your program.
Unfortunately, I didn't manage to make it run.

I've flashed a ESP8266 D1 mini with your .bin, and I can access the Wled interface on it without problems.

But when I launch WLEDAraSync.exe v1.0 the cmd windows launch, then close automatically without nothing written in it.
When I try with WLEDAraSync.exe v1.1, I got this tree warnings about missing files: 
ucrtbased.dll
VCRUNTIME140D.dll
MSVCP140D.dll

I've got the latest Armory Create installed on a STRIX X570-E Gaming, VCredist 2008 --> 2019 installed.

Could you figure out what happening ?

Regards.

**Comment by ShadyNawara** [comment]
Hi,
the window launching and closing automatically is most likely due to the wrong com port selected. the app defaults to COM5 so you should try running it like this "WLEDAraSync.exe COMX"

for the missing dlls I would suggest reinstalling [VC++ redist 2015](https://www.microsoft.com/en-us/download/details.aspx?id=52685)

I am a big fan of [OpenRGB](https://gitlab.com/CalcProgrammer1/OpenRGB) Now and you might want to take a look at it. its a great project.

**Comment by ShadyNawara** [comment]
created a new build that should fix the issue, let me know if it still doesnt work for you

**Comment by ZorK766** [comment]
Sorry for been long, but just tested, and it is working with 1.2 release. 
Regards.
